[package]
name = "rebaser"
version = "0.1.0"
edition = "2021"
rust-version = "1.64"
publish = false

[[bin]]
name = "rebaser"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
rebaser-server = { path = "../../lib/rebaser-server" }
si-service = { path = "../../lib/si-service" }
si-std = { path = "../../lib/si-std" }
