status = [
  "Merge Request Checks",
]
pr_status =[
  "Pull Request Checks",
]
block_labels = [
  "wip"
]
required_approvals = 0
delete_merged_branches = true
update_base_for_deletes = true
up_to_date_approvals = true
commit_title = "merge: ${PR_REFS}"
