---
#
# Project infrastructure
#
A-ci:
  - .ci/**/*
  - .github/**/*
  - Makefile
  - ./**/Makefile
A-docs:
  - docs/**/*

#
# System Initiative apps (i.e. webapps/ios apps/android apps)
#
A-corp:
  - app/corp/**/*
  - .prettierrc.js
A-web:
  - app/web/**/*
  - .prettierrc.js

#
# System Initiative bins (i.e. services/programs/binaries)
#
A-cyclone:
  - bin/cyclone/**/*
  - lib/cyclone-client/**/*
  - lib/cyclone-core/**/*
  - lib/cyclone-server/**/*
  - .cargo/**/*
  - Cargo.lock
  - rust-toolchain
  - rustfmt.toml
A-sdf:
  - bin/sdf/**/*
  - lib/sdf/**/*
  - .cargo/**/*
  - Cargo.lock
  - rust-toolchain
  - rustfmt.toml
A-veritech:
  - bin/veritech/**/*
  - lib/veritech/**/*
  - .cargo/**/*
  - Cargo.lock
  - rust-toolchain
  - rustfmt.toml
A-lang-js:
  - bin/lang-js/**/*
  - .prettierrc.js
A-si-discord-bot:
  - bin/si-discord-bot/**/*
  - .prettierrc.js

#
# System Initiative libs (i.e. crates/packages/libraries)
#
A-bytes-lines-codec:
  - lib/bytes-lines-codec/**/*
  - .cargo/**/*
  - Cargo.lock
  - rust-toolchain
  - rustfmt.toml
A-config-file:
  - lib/config-file/**/*
  - .cargo/**/*
  - Cargo.lock
  - rust-toolchain
  - rustfmt.toml
A-dal:
  - lib/dal/**/*
  - .cargo/**/*
  - Cargo.lock
  - rust-toolchain
  - rustfmt.toml
A-deadpool-cyclone:
  - lib/deadpool-cyclone/**/*
  - .cargo/**/*
  - Cargo.lock
  - rust-toolchain
  - rustfmt.toml
A-si-data:
  - lib/si-data/**/*
  - .cargo/**/*
  - Cargo.lock
  - rust-toolchain
  - rustfmt.toml
A-si-settings:
  - lib/si-settings/**/*
  - .cargo/**/*
  - Cargo.lock
  - rust-toolchain
  - rustfmt.toml
A-si-test-macros:
  - lib/si-test-macros/**/*
  - .cargo/**/*
  - Cargo.lock
  - rust-toolchain
  - rustfmt.toml
A-telemetry-rs:
  - lib/telemetry-rs/**/*
  - .cargo/**/*
  - Cargo.lock
  - rust-toolchain
  - rustfmt.toml

#
# Third-party development images
#
A-nats:
  - component/nats/**/*
A-otelcol:
  - component/otelcol/**/*
A-postgres:
  - component/postgres/**/*
A-skopeo:
  - component/skopeo/**/*
