[profile.release]
debug = true

[workspace]
resolver = "2"
members = [
    "bin/council",
    "bin/cyclone",
    "bin/gen-var-defs",
    "bin/pinga",
    "bin/sdf",
    "bin/veritech",
    "lib/bytes-lines-codec",
    "lib/config-file",
    "lib/cyclone-client",
    "lib/cyclone-core",
    "lib/cyclone-server",
    "lib/council-server",
    "lib/dal",
    "lib/dal-test",
    "lib/deadpool-cyclone",
    "lib/nats-subscriber",
    "lib/object-tree",
    "lib/pinga-server",
    "lib/sdf-server",
    "lib/si-data-nats",
    "lib/si-data-pg",
    "lib/si-pkg",
    "lib/si-settings",
    "lib/si-std",
    "lib/si-test-macros",
    "lib/si-posthog-rs",
    "lib/telemetry-application-rs",
    "lib/telemetry-rs",
    "lib/veritech-client",
    "lib/veritech-core",
    "lib/veritech-server",
]

[workspace.dependencies]
async-trait = "0.1.68"
base64 = "0.21.0"
chrono = { version = "0.4.24", features = ["serde"] }
clap = { version = "4.2.7", features = ["derive", "color", "env", "wrap_help"] }
color-eyre = { version = "0.6.2" }
config = { version = "0.13.3", default-features = false, features = ["toml"]}
crossbeam-channel = "0.5.8"
deadpool = { version = "0.9.5", features = ["rt_tokio_1"] }
directories = "5.0.1"
derive_builder = "0.12.0"
futures = "0.3.28"
nats = { version = "0.24.0" }
nix = "0.26.2"
nkeys = "0.2.0"
opentelemetry = { version = "~0.18.0", features = ["rt-tokio", "trace"] } # pinned, pending new release of tracing-opentelemetry, 0.18
opentelemetry-otlp = "~0.11.0" # pinned, pending new release of tracing-opentelemetry, post 0.18
opentelemetry-semantic-conventions = "~0.10.0" # pinned, pending new release of tracing-opentelemetry, post 0.18
pathdiff = "0.2.1"
serde = { version = "1.0.160", features = ["derive", "rc"] }
serde_json = { version = "1.0.96", features = ["preserve_order"] }
serde_toml = { version = "0.7.3", package = "toml" }
serde_with = "3.0.0"
serde_yaml = "0.9.21"
sodiumoxide = "0.2.7"
tempfile = "3.5.0"
thiserror = "1.0.40"
tokio = { version = "1.28.0", features = ["full"] }
tokio-test = "0.4.2"
tracing = { version = "0.1" }
tracing-opentelemetry = "0.18.0"
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "std"] }
ulid = { version = "1.0.0", features = ["serde"] }
uuid = { version = "1.3.2", features = ["serde", "v4"] }

[patch.crates-io]
# pending a potential merge and release of https://github.com/softprops/hyperlocal/pull/53
hyperlocal = { git = "https://github.com/fnichol/hyperlocal.git", branch = "pub-unix-stream" }
