[profile.release]
debug = true

[workspace]
members = [
    "bin/council",
    "bin/cyclone",
    "bin/gen-var-defs",
    "bin/pinga",
    "bin/sdf",
    "bin/veritech",
    "lib/bytes-lines-codec",
    "lib/config-file",
    "lib/cyclone-client",
    "lib/cyclone-core",
    "lib/cyclone-server",
    "lib/council",
    "lib/dal",
    "lib/dal-test",
    "lib/deadpool-cyclone",
    "lib/nats-subscriber",
    "lib/object-tree",
    "lib/sdf",
    "lib/si-data-nats",
    "lib/si-data-pg",
    "lib/si-pkg",
    "lib/si-settings",
    "lib/si-std",
    "lib/si-test-macros",
    "lib/telemetry-application-rs",
    "lib/telemetry-rs",
    "lib/veritech-client",
    "lib/veritech-core",
    "lib/veritech-server",
]

[patch.crates-io]
# pending a potential merge and release of https://github.com/softprops/hyperlocal/pull/53
hyperlocal = { git = "https://github.com/fnichol/hyperlocal.git", branch = "pub-unix-stream" }
