[package]
name = "pinga"
version = "0.1.0"
edition = "2021"
rust-version = "1.56"
publish = false

[[bin]]
name = "pinga"
path = "src/main.rs"

[dependencies]
clap = { version = "3.1.12", features = ["derive", "color", "env"] }
color-eyre = { version = "0.6.1" }
telemetry = { path = "../../lib/telemetry-rs", features = ["application"] }
tokio = { version = "1.12.0", features = ["full"] }
thiserror = { version = "1.0" }
futures = "0.3"

sdf = { path = "../../lib/sdf" }
si-data = { path = "../../lib/si-data" }
veritech = { path = "../../lib/veritech", features = ["client", "server"] }
dal = { path = "../../lib/dal" }
faktory-async = { git = "https://github.com/systeminit/faktory-async", branch = "main" }
