name: Feature Request
description: Request a new feature and/or enhancement to an existing feature
labels: [ linear, feature-request ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request! Please fill the form below.

        If you have a question or topic of conversation that does not fit our issue template(s), reach out to us [on Discord](https://discord.com/invite/system-init).
  - type: textarea
    id: is-it-a-problem
    attributes:
      label: Is this issue related to an issue?.
      description: Please give us a clear and concise description of what the problem is, e.g. I'm always frustrated when [...], or link a github issue where it's already discussed,
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the outcome you'd like from us
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/systeminit/si/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: textarea
    id: ctx
    attributes:
      label: Additional context
      description: Anything else you would like to add
    validations:
      required: false