[package]
name = "gen-var-defs"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.51"
clap = { version = "4.1.6", features = ["derive", "color", "env", "wrap_help"] }
color-eyre = { version = "0.6.1" }
convert_case = "0.6.0"
dal = { path = "../../lib/dal" }
derive_builder = { version = "0.12" }
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
si-data-nats = { path = "../../lib/si-data-nats" }
si-data-pg = { path = "../../lib/si-data-pg" }
si-settings = { path = "../../lib/si-settings" }
telemetry-application = { path = "../../lib/telemetry-application-rs" }
thiserror = { version = "1.0" }
tokio = { version = "1.12.0", features = ["full"] }
uuid = { version = "1.1.2", features = ["serde", "v4"] }
veritech-client = { path = "../../lib/veritech-client" }
