[package]
name = "gen-var-defs"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.6", features = ["derive", "color", "env", "wrap_help"] }
color-eyre = { version = "0.6.1" }
telemetry-application = { path = "../../lib/telemetry-application-rs" }
tokio = { version = "1.12.0", features = ["full"] }
thiserror = { version = "1.0" }
futures = "0.3"

si-data-faktory = { path = "../../lib/si-data-faktory" }
si-data-nats = { path = "../../lib/si-data-nats" }
si-data-pg = { path = "../../lib/si-data-pg" }
veritech-client = { path = "../../lib/veritech-client" }
dal = { path = "../../lib/dal" }
faktory-async = { git = "https://github.com/systeminit/faktory-async", branch = "main" }

derive_builder = { version = "0.11.2" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
si-settings = { path = "../../lib/si-settings" }
uuid = { version = "1.1.2", features = ["serde", "v4"] }

async-trait = "0.1.51"
convert_case = "0.6.0"

