[package]
name = "sdf-cli"
version = "0.1.0"
edition = "2021"
rust-version = "1.56"
publish = false

[[bin]]
name = "sdf"
path = "src/main.rs"

[dependencies]
clap = { version = "4.0.14", features = ["derive", "color", "env", "wrap_help"] }
color-eyre = { version = "0.6.1" }
sdf = { path = "../../lib/sdf" }
telemetry = { path = "../../lib/telemetry-rs", features = ["application"] }
tokio = { version = "1.12.0", features = ["full"] }
faktory-async = { git = "https://github.com/systeminit/faktory-async", branch = "main" }
