[package]
name = "sdf"
version = "0.1.0"
edition = "2021"
rust-version = "1.64"
publish = false

[[bin]]
name = "sdf"
path = "src/main.rs"

[dependencies]
clap = { version = "4.0.14", features = ["derive", "color", "env", "wrap_help"] }
color-eyre = { version = "0.6.1" }
sdf-server = { path = "../../lib/sdf-server" }
telemetry-application = { path = "../../lib/telemetry-application-rs" }
tokio = { version = "1.12.0", features = ["full"] }
