global:
  scrape_interval: 100ms
scrape_configs:
 - job_name: service_metrics
   static_configs:
    - targets:
       - otelcol:9090
 - job_name: firecracker
   static_configs:
    - targets:
       - process-exporter:9256
 - job_name: node-exporter
   static_configs:
    - targets:
      - node-exporter:9100
