sources:
  docker:
    type: "docker_logs"
  $SI_SERVICE-journal:
    type: "journald"
    include_units: ["$SI_SERVICE"]
    journal_directory: "/var/log/journal"
  sdf-migration:
    type: "journald"
    include_matches:
      SYSLOG_IDENTIFIER: ["sdf-migration"]
    journal_directory: "/var/log/journal"

sinks:
  cloudwatch:
    type: "aws_cloudwatch_logs"
    inputs: ["$SI_SERVICE-journal", "sdf-migration"]
    compression: "gzip"
    encoding:
      codec: "text"
    region: "us-east-1"
    group_name: "/ec2/$SI_HOSTENV-$SI_SERVICE"
    stream_name: "{{ host }}"
