[package]
name = "veritech-cli"
version = "0.1.0"
edition = "2021"
rust-version = "1.56"
publish = false

[[bin]]
name = "veritech"
path = "src/main.rs"

[dependencies]
clap = { version = "4.0.14", features = ["derive", "color", "env", "wrap_help"] }
color-eyre = { version = "0.6.1" }
telemetry = { path = "../../lib/telemetry-rs", features = ["application"] }
tokio = { version = "1.12.0", features = ["full"] }
veritech-server = { path = "../../lib/veritech-server" }
