[workspace]

[package]
# Pseudo-package whose dependencies are imported and buckified
name = "third-party"
version = "0.0.0"
publish = false
edition = "2021"

# Dummy target to keep Cargo happy
[lib]
path = "/dev/null"

# List of packages to be imported, with version constraints, features
# and all options Cargo supports.
[dependencies]
serde = { version = "1.0.123", features = ["derive"] }
