---
name: build-docker-image

on:
  workflow_call:
    inputs:
      component_name:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true

jobs:
  build-image:
    name: Build ${{ inputs.component_name }} Docker Image
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - id: buildx
        uses: docker/setup-buildx-action@v2
      - id: login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - id: release
        name: make release//${{ inputs.component_name }}
        run: |
          : make release//${{ inputs.component_name }}
          echo "::group::Building and publishing image"
          make release//${{ inputs.component_name }}
          echo "::endgroup::"
          echo "::group::Manifest info"
          jq . <tmp/release-$(basename ${{ inputs.component_name }}).manifest.json
          echo "::endgroup::"
          echo "manifest=$(
            cat tmp/release-$(basename ${{ inputs.component_name }}).manifest.json
          )" >> $GITHUB_OUTPUT
      - name: report
        if: success()
        run: |
          : report
          echo 'DockerHub URL: ${{ fromJSON(steps.release.outputs.manifest).image_url }}'
          echo 'GitHub Commit URL: ${{ fromJSON(steps.release.outputs.manifest).commit_url }}'
