name: command-dispatch
on:
  issue_comment:
    types:
      - created
      - edited
jobs:
  command-dispatch-for-prs:
    name: command-dispatch-for-prs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - uses: peter-evans/slash-command-dispatch@v2
        with:
          commands: run-build
          issue-type: pull-request
          permission: write
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          repository: systeminit/si
          token: ${{ secrets.GITHUB_TOKEN }}