name: Crons

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes

# We will wait until these tests finish before starting a deploy
concurrency:
  group: deploy-production
  cancel-in-progress: false

jobs:
  e2e-validation:
    uses: ./.github/workflows/e2e-validation.yml
    with:
      environment: production
    secrets: inherit
  api-test:
    uses: ./.github/workflows/run-api-test.yml
    with:
      environment: production
    secrets: inherit
