on:
  push:
    tags:
      - '.*(sdf|rebaser|pinga|web|veritech).*'

jobs:
  parse-tag:
    runs-on: ubuntu-latest
    outputs:
      service: ${{ steps.service.outputs.service }}
    steps:
      - id: service
        run: |
            echo "service=$(echo "${{ github.ref_name }}" | awk -F'/' '{print $2}')" >> "$GITHUB_OUTPUT"

  deploy-tools-prod:
    needs: parse-tag
    uses: ./.github/workflows/deploy-stack.yml
    with:
      environment: tools
      service: ${{ needs.parse-tag.outputs.service }}
      version: stable
      deploy-type: binary
    secrets: inherit
    continue-on-error: true
  full-deploy-on-failure:
    if: failure() 
    uses: ./.github/workflows/deploy-stack.yml
    with:
      environment: tools
      service: all
      version: stable
      deploy-type: instance
    secrets: inherit
    needs: deploy-tools-prod