name: Deploy Services

run-name: Deploy of ${{ inputs.service }} to ${{ inputs.environment }} by @${{ github.actor }}

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        default: "tools"
      service:
        type: string
        required: true
        default: "all"
      version:
        type: string
        required: true
        default: "stable"
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        description: "where to deploy"
        default: "tools"
        options:
          - tools
          - production
      service:
        type: choice
        required: true
        description: "service to deploy"
        options:
          - all
          - pinga
          - rebaser
          - sdf
          - veritech
          - web
      version:
        type: string
        required: true
        description: "version to deploy"
        default: "stable"

jobs:
  invalidate-cache:
    uses: ./.github/workflows/invalidate-cache.yml
    with:
      environment: shared
    secrets: inherit

  deploy-service:
    needs: invalidate-cache
    if: ${{ inputs.service != 'all' }}
    uses: ./.github/workflows/deploy-service.yml
    with:
      environment: ${{ inputs.environment }}
      service: ${{ inputs.service }}
      version: ${{ inputs.version }}
    secrets: inherit

  deploy-services:
    needs: invalidate-cache
    if: ${{ inputs.service == 'all' }}
    strategy:
     fail-fast: false
     matrix:
      service: ["pinga", "rebaser", "sdf", "veritech", "web"]
    uses: ./.github/workflows/deploy-service.yml
    with:
      environment: ${{ inputs.environment }}
      service: ${{ matrix.service }}
      version: ${{ inputs.version }}
    secrets: inherit

  set-init:
    needs: invalidate-cache
    uses: ./.github/workflows/set-init-version.yml
    with:
      environment: ${{ inputs.environment }}
      service: ${{ inputs.service }}
      version: ${{ inputs.version }}
    secrets: inherit
