name: Deploy Module Index
"on":
  workflow_dispatch: {}

env:
  MODULE_INDEX_CLUSTER: shared-cluster
  MODULE_INDEX_SERVICE: module-index

jobs:
  deploy:
    name: Deploy latest stable image
    environment: shared
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1
      - name: Trigger ECS Deploy
        run: |
          aws ecs update-service --cluster ${{ env.MODULE_INDEX_CLUSTER }} --service ${{ env.MODULE_INDEX_SERVICE }} --force-new-deployment
