name: Deploy Services

run-name: Deploy to ${{ inputs.environment }} by @${{ github.actor }}

on:
  workflow_call:
    inputs:
      environment:
        type: string
        default: "tools"
      version:
        type: string
        default: "stable"

  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        description: "Where to deploy"
        default: "tools"
        options:
          - tools
          - production
      version:
        type: string
        required: true
        description: "version to deploy"
        default: "stable"

jobs:
  set-service-versions:
    uses: ./.github/workflows/set-service-version.yml
    strategy:
     fail-fast: false
     matrix:
      service: [ "pinga", "rebaser", "sdf", "veritech" ]
    with:
      environment: ${{ inputs.environment }}
      service: ${{ matrix.service }}
      version: ${{ inputs.version }}
    secrets: inherit

  set-maintenance-mode:
    uses: ./.github/workflows/set-maintenance-mode.yml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit

  down: # the backend services
    needs:
      - set-maintenance-mode
    strategy:
     fail-fast: false
     matrix:
      service: [ "pinga", "rebaser", "sdf" ]
    uses: ./.github/workflows/down-service.yml
    with:
      environment: ${{ inputs.environment }}
      service: ${{ matrix.service }}
    secrets: inherit

  upgrade-web:
    needs:
      - set-maintenance-mode
    uses: ./.github/workflows/upgrade-web.yml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit

  upgrade: # the backend services
    needs:
      - set-service-versions
      - down
    strategy:
     fail-fast: false
     matrix:
       service: [ "pinga", "rebaser", "sdf", "veritech" ]
    uses: ./.github/workflows/upgrade-service.yml
    with:
      environment: ${{ inputs.environment }}
      service: ${{ matrix.service }}
    secrets: inherit

  up: # the backend services
    needs:
      - upgrade
    strategy:
     fail-fast: false
     matrix:
      service: [ "pinga", "rebaser", "veritech" ]
    uses: ./.github/workflows/up-service.yml
    with:
      environment: ${{ inputs.environment }}
      service: ${{ matrix.service }}
    secrets: inherit

  migrate-and-up-sdf:
    needs:
      - up
    uses: ./.github/workflows/migrate-sdf.yml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit

  e2e-validation:
    # We want to ensure that in-progress cron runs against tools-prod
    # are canceled when we do a deploy so they don't fail erroneously
    concurrency:
      group: e2e-${{ inputs.environment }}
      cancel-in-progress: true
    needs:
      - upgrade-web
      - migrate-and-up-sdf
    if: always()
    uses: ./.github/workflows/e2e-validation.yml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit
