name: Deploy Auth API
"on":
  workflow_dispatch: {}

env:
  AUTH_API_CLUSTER: shared-cluster
  AUTH_API_SERVICE: auth-api

jobs:
  deploy:
    name: Deploy latest stable image
    environment: shared
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1
      - name: Trigger ECS Deploy
        run: |
          aws ecs update-service --cluster ${{ env.AUTH_API_CLUSTER }} --service ${{ env.AUTH_API_SERVICE }} --force-new-deployment
