name: deploy-after-wait

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        description: "Where to deploy to"
        default: "tools"
        options:
          - tools
          - production
      wait_duration:
        type: string
        required: true
        description: "How long to wait before deploying"
        default: "300" # 5 minutes

jobs:
  wait:
    name: wait
    runs-on: ubuntu-latest
    steps:
      - name: wait
        run: |
          echo "Sleeping for ${{ inputs.wait_duration }}"
          sleep ${{ inputs.wait_duration }}

  deploy:
    uses: ./.github/workflows/deploy-stack.yml
    needs: wait
    with:
      environment: ${{ inputs.environment }}
      version: stable
    secrets: inherit

  on-failure:
    runs-on: ubuntu-latest
    needs: deploy
    if: failure()
    steps:
      - run: |
          curl -X POST \
            -H 'Content-type: application/json' \
            --data "{\"text\": \":si: Deployment to ${{ inputs.environment }} failed: <https://github.com/systeminit/si/actions/runs/$GITHUB_RUN_ID|:ship: Link>\"}" ${{ secrets.SLACK_WEBHOOK_URL }}
