name: Deploy Auth API
"on":
  workflow_dispatch: {}

env:
  AUTH_API_CLUSTER: shared-cluster
  AUTH_API_SERVICE: auth-api

# Required for IDP JWT and actions/checkout
permissions:
      id-token: write
      contents: read
   
jobs:
  deploy:
    name: Deploy latest stable image
    environment: shared
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ vars.AWS_ASSUME_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-1
      - name: Trigger ECS Deploy
        run: |
          aws ecs update-service --cluster ${{ env.AUTH_API_CLUSTER }} --service ${{ env.AUTH_API_SERVICE }} --force-new-deployment
