on:
  push:
    tags:
      - 'tools/deploy/*'

jobs:
  deploy-tools-prod:
    uses: ./.github/workflows/deploy-stack.yml
    with:
      environment: tools
      version: stable
    secrets: inherit
