on:
  push:
    branches:
      - main
jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4
      - name: "Run FOSSA Scan"
        uses: fossas/fossa-action@v1.3.1
        with:
          api-key: ${{secrets.FOSSA_API_KEY}}
