name: Nightly end-to-end Tests
on:
  schedule:
    - cron:  '0 5 * * *'
  workflow_dispatch: { }

jobs:
  run:
    timeout-minutes: 60
    runs-on: self-hosted
    name: Whiskers!
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ECS_DEPLOYMENT_USER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ECS_DEPLOYMENT_USER_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_ECS_REGION }}
      - name: Install node, pnpm, dependencies
        uses: ./.github/actions/node-pnpm-setup
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Login Docker
        id: login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Create Whiskers
        run: cargo test --package sdf-server --test api service_tests::scenario::model_and_fix_flow_whiskers::model_and_fix_flow_whiskers -- --ignored --exact
        working-directory:
        env:
          SI_TEST_BUILTIN_SCHEMAS: "aws region,aws ami,aws keypair,aws ec2,aws securitygroup,aws ingress,docker image,coreos butane"