name: Production Crons

on:
  schedule:
    # Weekdays: Every 15 minutes except 7:45 PM and 8:00 PM UTC
    - cron: "0-44/15 0-19 * * 1-5"  # Every 15 minutes from 12:00 AM to 7:44 PM UTC (Monday to Friday)
    - cron: "15-59/15 20-23 * * 1-5" # Every 15 minutes from 8:15 PM to 11:59 PM UTC (Monday to Friday)
    # Weekends: Every 15 minutes including 8:00 PM UTC
    - cron: "*/15 * * * 6,0" # Every 15 minutes on Saturday (6) and Sunday (0)

# Prod deployment cron is currently disabled, but this should `not` cancel the synthetic
# e2e runner cron
concurrency:
  group: deploy-production
  cancel-in-progress: false

jobs:
  e2e-validation:
    uses: ./.github/workflows/e2e-validation.yml
    with:
      environment: production
    secrets: inherit
  api-test:
    uses: ./.github/workflows/run-api-test.yml
    with:
      environment: production
    secrets: inherit
