name: Production Service Restart Cron

on:
  schedule:
    - cron: "0 20 * * 6,0" # Deploys every weekend at 8pm UTC

concurrency:
  group: restart-production
  cancel-in-progress: false

jobs:
  restart-production:
    uses: ./.github/workflows/deploy-service-restart.yml
    with:
      environment: production
    secrets: inherit
