name: Production Deploy Cron

on:
  schedule:
    - cron: "45 14 * * 1-5" # Deploys every weekday at 3pm UTC

jobs:
  deploy-production:
    uses: ./.github/workflows/deploy-stack.yml
    with:
      environment: production
      wait_duration: 900
    secrets: inherit
