name: promote-nats

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/promote-image.yml
      - .github/workflows/promote-nats.yml
      - component/nats/**

jobs:
  promote:
    uses: ./.github/workflows/promote-image.yml
    with:
      component_name: component/nats
    secrets:
      SLACKBOT_TOKEN: ${{ secrets.SLACKBOT_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
