name: promote-council

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/promote-image.yml
      - .github/workflows/promote-council.yml
      - .cargo/**
      - Cargo.*
      - bin/council/**
      - lib/council/**
      - lib/config-file/**
      - lib/dal/**
      - lib/sdf/**
      - lib/si-data-nats/**
      - lib/si-data-pg/**
      - lib/nats-subscriber/**
      - lib/object-tree/**
      - lib/si-pkg/**
      - lib/si-settings/**
      - lib/si-std/**
      - lib/telemetry-application-rs/**
      - lib/telemetry-rs/**
      - lib/veritech-client/**
      - lib/veritech-core/**
      - rust-toolchain
      - rustfmt.toml

jobs:
  promote:
    uses: ./.github/workflows/promote-image.yml
    with:
      component_name: bin/council
    secrets:
      SLACKBOT_TOKEN: ${{ secrets.SLACKBOT_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
