name: promote-web

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/promote-image.yml
      - .github/workflows/promote-web.yml
      - .prettierrc.js
      - babel.config.js
      - app/web/**

jobs:
  promote:
    uses: ./.github/workflows/promote-image.yml
    with:
      component_name: app/web
    secrets:
      SLACKBOT_TOKEN: ${{ secrets.SLACKBOT_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
