name: Set init version

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: "where to deploy"
      service:
        type: string
        required: true
        description: "service to deploy"
      version:
        type: string
        required: true
        description: "version to deploy"

jobs:
  deploy:
    name: Set init version
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials for production
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Set init version
        if: ${{ inputs.service != 'web' }}
        run: |
            ENVIRONMENT="${{ inputs.environment }}"
            VERSION="${{ inputs.version }}"
            if docker manifest inspect "systeminit/init:$VERSION" >/dev/null 2>&1; then
              aws ssm put-parameter --name "${ENVIRONMENT}-si-version-init" --value "$VERSION" --type "String" --overwrite
            else
              aws ssm put-parameter --name "${ENVIRONMENT}-si-version-init" --value "stable" --type "String" --overwrite
            fi
