name: Upgrade Service

run-name: Upgrading ${{ inputs.service }}

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: "where to deploy"
      service:
        type: string

jobs:
  upgrade:
    environment: ${{ inputs.environment }}
    name: ${{ inputs.service }} Upgrade
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Configure AWS credentials for ${{ inputs.environment }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Down service
        run: |
          component/toolbox/awsi.sh service-state -p pull-from-env -r us-east-1 -a y -s ${{ inputs.service }} -S down

      - name: Upgrade service
        run: |
          component/toolbox/awsi.sh upgrade -p pull-from-env -r us-east-1 -a y -s ${{ inputs.service }} -e ${{ inputs.environment }}

      - name: Up service
        run: |
          component/toolbox/awsi.sh service-state -p pull-from-env -r us-east-1 -a y -s ${{ inputs.service }} -S up

  on-failure:
    uses: ./.github/workflows/instance-refresh.yml
    needs: upgrade
    if: failure()
    with:
      environment: ${{ inputs.environment }}
      service: ${{ inputs.service }}
    secrets: inherit
