---
version: "3"

services:
  sdf:
    image: "fedora:latest"
    volumes:
      - type: bind
        source: "${REPOPATH:-..}/target/debug/sdf"
        target: "/usr/local/bin/sdf"
        read_only: true
      - type: bind
        source: "${REPOPATH:-..}/bin/sdf/src/dev.jwt_secret_key.bin"
        target: "/run/sdf/jwt_secret_key.bin"
        read_only: true
      - type: bind
        source: "${REPOPATH:-..}/lib/cyclone-server/src/dev.encryption.key"
        target: "/run/sdf/cyclone_encryption.key"
        read_only: true
    entrypoint:
      - "/usr/local/bin/sdf"

  veritech:
    image: "fedora:latest"
    volumes:
      - type: bind
        source: "${REPOPATH:-..}/target/debug/veritech"
        target: "/usr/local/bin/veritech"
        read_only: true
      - type: bind
        source: "${REPOPATH:-..}/target/debug/cyclone"
        target: "/usr/local/bin/cyclone"
        read_only: true
      - type: bind
        source: "${REPOPATH:-..}/lib/cyclone-server/src/dev.decryption.key"
        target: "/run/cyclone/decryption.key"
        read_only: true
      - type: bind
        source: "${REPOPATH:-..}/bin/lang-js/target/lang-js"
        target: "/usr/local/bin/lang-js"
        read_only: true
    entrypoint:
      - "/usr/local/bin/veritech"

  web:
    image: "nginx:1.21.4-alpine"
    # NOTE(nick): "dist" is a directory and the other mounts are files. This might help when debugging permissions errors
    # SELinux, volume mounts, etc.
    volumes:
      - type: bind 
        source: "${REPOPATH:-..}/app/web/dist"
        target: "/usr/share/nginx/html"
        read_only: true
      - type: bind 
        source: "${REPOPATH:-..}/app/web/nginx.conf"
        target: "/etc/nginx/conf.d/default.conf"
        read_only: true
      - type: bind
        source: "${REPOPATH:-..}/app/web/nginx/dhparam.pem"
        target: "/etc/ssl/certs/dhparam.pem"
        read_only: true
      - type: bind
        source: "${REPOPATH:-..}/app/web/nginx/nginx-selfsigned.crt"
        target: "/etc/ssl/certs/nginx-selfsigned.crt"
        read_only: true
      - type: bind 
        source: "${REPOPATH:-..}/app/web/nginx/nginx-selfsigned.key"
        target: "/etc/ssl/certs/nginx-selfsigned.key"
        read_only: true

  pinga:
    image: "fedora:latest"
    volumes:
      - type: bind 
        source: "${REPOPATH:-..}/target/debug/pinga"
        target: "/usr/local/bin/pinga"
        read_only: true
      - type: bind
        source: "${REPOPATH:-..}/lib/cyclone-server/src/dev.encryption.key"
        target: "/run/pinga/cyclone_encryption.key"
        read_only: true
    entrypoint:
      - "/usr/local/bin/pinga"

  council:
    image: "fedora:latest"
    volumes:
      - type: bind 
        source: "${REPOPATH:-..}/target/debug/council"
        target: "/usr/local/bin/council"
        read_only: true
    entrypoint:
      - "/usr/local/bin/council"
