---
version: "3"

services:
  web:
    image: "nginx:1.21.4-alpine"
    # NOTE(nick): "dist" is a directory and the other mounts are files. This might help when debugging permissions errors
    # SELinux, volume mounts, etc.
    volumes:
      - "${REPOPATH:-..}/app/web/dist:/usr/share/nginx/html"
      - "${REPOPATH:-..}/app/web/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "${REPOPATH:-..}/app/web/nginx/dhparam.pem:/etc/ssl/certs/dhparam.pem"
      - "${REPOPATH:-..}/app/web/nginx/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt"
      - "${REPOPATH:-..}/app/web/nginx/nginx-selfsigned.key:/etc/ssl/certs/nginx-selfsigned.key"
  sdf:
    volumes:
      - "${REPOPATH:-..}/bin/sdf/src/dev.jwt_secret_key.bin:/run/sdf/jwt_secret_key.bin:ro"
      - "${REPOPATH:-..}/lib/cyclone/src/dev.encryption.key:/run/sdf/cyclone_encryption.key:ro"
  veritech:
    volumes:
      - "${REPOPATH:-..}/lib/cyclone/src/dev.decryption.key:/run/cyclone/decryption.key:ro"
  pinga:
    image: "fedora:latest"
    volumes:
      - "${REPOPATH:-..}/target/debug/pinga:/usr/local/bin/pinga"
      - "${REPOPATH:-..}/bin/pinga/src/dev.jwt_secret_key.bin:/run/pinga/jwt_secret_key.bin:ro"
      - "${REPOPATH:-..}/lib/cyclone/src/dev.encryption.key:/run/pinga/cyclone_encryption.key:ro"
    entrypoint:
      - "/usr/local/bin/pinga"
